services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: student_db
    ports:
      - "5435:5432"

  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"

  fastapi-app:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "9090:8000"
    env_file:
      - .env
